name: Deploy
on:
  push:
    branches: [main]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          port: 22
          script: |
            cd ${{secrets.REMOTE_TARGET}}
            git pull origin main
            pnpm i
            pnpm run build
            pm2 restart connect-api